### ISSUE TITLE
About Markvis-Pie Error

### ISSUE THREAD

**Issue by jasperliu911** [geekplux/markvis#14]
![image](https://github.com/geekplux/markvis/assets/72329902/ab2a4b30-f50b-43c6-9995-db5ea3aef068)
![image](https://github.com/geekplux/markvis/assets/72329902/8b4a93b0-b8ed-42ab-a39e-63a026d40443)

When I installed this plug-in in the project, I found that after entering a piece of pie chart syntax, the console output a series of errors. This error seems to be that the argument array has a length, but it is [' ']. I hope the author can see it reply to this question in a timely manner. Thanks

**Comment by jasperliu911** [comment]
![image](https://github.com/geekplux/markvis/assets/72329902/4a88fc20-fabd-477d-9a63-705382920c36)
Today I found the source code and found that the schemeCategory20d attribute does not exist in d3, only the schemeCategory10 attribute

**Comment by jasperliu911** [comment]
![image](https://github.com/geekplux/markvis/assets/72329902/a22e7933-0916-41d4-9eda-bbc677341756)
My D3 version is 7.8.5

**Comment by jasperliu911** [comment]
![image](https://github.com/geekplux/markvis/assets/72329902/73f1ffbe-8c1d-40c2-bd6a-a3c2ac6b2528)
The D3 dependency package has removed the three attributes schemeCategory20b, schemeCategory20c, schemeCategory20 after version 4.13.0. So you need to change _d3.scaleOrdinal(_d3.schemeCategory20b) in the markvis-pie dependency package to _d3.scaleOrdinal(_d3 .schemeCategory10)

**Comment by geekplux** [comment]
Thanks for your found. Yes, this project is truly outdated, which is needed to update the deps.

**Comment by geekplux** [comment]
fixed by https://github.com/geekplux/markvis/commit/22005f48a2b6b6cb2f8ba11adeb9b51c3620e0a9
