### ISSUE TITLE
About title Error

### ISSUE THREAD

**Issue by jasperliu911** [geekplux/markvis#15]
![image](https://github.com/geekplux/markvis/assets/72329902/08e2e4f0-3e30-42da-8a7e-c40952950c1c)

Today I suddenly discovered that after installing the markvis plug-in, titles above level three cannot be displayed normally, and the output html becomes <pre><code class="language-thirdTitle"></code></pre>

**Comment by jasperliu911** [comment]
I already know the reason, because in your plugin: marvis, the markdown-it-fence plugin version specified in package.json is 0.0.2. In this version of markdown-it-fence, there will be a problem that the third-level title cannot be displayed; when I browsed your markdown-it-fence repository, I saw in Issues that you have released the latest version v0. 1.3, when I reinstalled the plugin, everything went back to normal. This problem also occurs in your demo page, so please update the version of markdown-it-fence in marvis in time.

**Comment by geekplux** [comment]
fixed by https://github.com/geekplux/markvis/commit/22005f48a2b6b6cb2f8ba11adeb9b51c3620e0a9
