### ISSUE TITLE
Wrong values

### ISSUE THREAD

**Issue by marcelpi** [geekplux/markvis#5]
![screenshot 2017-07-18 16 49 59](https://user-images.githubusercontent.com/7136479/28320769-1b06de8a-6bda-11e7-8bf4-68b6d17fad44.png)

Chart interpolates the wrong values. Please see attached image.

**Comment by geekplux** [comment]
Hi, Marcel, thanks your feedback. 

You can use `isCurve: false` to make line be straight:

```vis
layout: line
isCurve: false
```

reference: 

- https://github.com/geekplux/markvis-line/blob/master/src/index.js#L90
- https://github.com/d3/d3-shape#curveBasis
