### ISSUE TITLE
Is it possible to change color scheme of a pie chart from markdown?

### ISSUE THREAD

**Issue by nt0xa** [geekplux/markvis#9]
There are multiple color schemes available in d3: `schemeAccent`, `schemeDark`, `schemeCategory10`, etc. Can I set color scheme of a pie chart from markdown?

**Comment by geekplux** [comment]
https://github.com/geekplux/markvis-pie/blob/master/src/index.js#L68

I think it's possible to change the scheme to an optional config. You now can change pie color by style.

**Comment by nt0xa** [comment]
Thank you!
I got the following solution:

```vis
layout: pie
container: <div id="chart-1"></div>
selector: '#chart-1'
style: |
    #chart-1 .arc:nth-child(1) path {
        fill: red !important;
    }
    #chart-1 .arc:nth-child(2) path {
        fill: blue !important;
    }
data: [
  { key: 0, value: 5 },
  { key: 1, value: 4 },
]
```
